### ISSUE TITLE
Pobieranie folderu nie działa

### ISSUE THREAD

**Issue by bmariusz** [H4wk507/cda-dl#12]
```
❯ cda-dl --login mariusz.blaszczak@gmail.com https://www.cda.pl/thechosen/folder/64534728/vfilm
Podaj hasło dla mariusz.blaszczak@gmail.com:
╭────────────────────────────────────────────────────────────────────── Foldery ──────────────────────────────────────────────────────────────────────╮
│                                                                                                                                                     │
│                                                                                                                                                     │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Traceback (most recent call last):
  File "/Users/mblaszczak/.pyenv/versions/3.13.0/bin/cda-dl", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/Users/mblaszczak/.pyenv/versions/3.13.0/lib/python3.13/site-packages/cda_dl/main.py", line 110, in main
    Downloader(args)
    ~~~~~~~~~~^^^^^^
  File "/Users/mblaszczak/.pyenv/versions/3.13.0/lib/python3.13/site-packages/cda_dl/downloader.py", line 66, in __init__
    asyncio.run(self.main())
    ~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/mblaszczak/.pyenv/versions/3.13.0/lib/python3.13/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "/Users/mblaszczak/.pyenv/versions/3.13.0/lib/python3.13/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/Users/mblaszczak/.pyenv/versions/3.13.0/lib/python3.13/asyncio/base_events.py", line 721, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/Users/mblaszczak/.pyenv/versions/3.13.0/lib/python3.13/site-packages/cda_dl/downloader.py", line 83, in main
    await self.download_folders(session)
  File "/Users/mblaszczak/.pyenv/versions/3.13.0/lib/python3.13/site-packages/cda_dl/downloader.py", line 186, in download_folders
    await Folder(folder_url, session, self.ui).download_folder(
        self.download_options, self.download_state
    )
  File "/Users/mblaszczak/.pyenv/versions/3.13.0/lib/python3.13/site-packages/cda_dl/folder.py", line 51, in download_folder
    self.videos = await self.get_videos_from_folder()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mblaszczak/.pyenv/versions/3.13.0/lib/python3.13/site-packages/cda_dl/folder.py", line 137, in get_videos_from_folder
    self.url = self.get_next_page_url()
               ~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/mblaszczak/.pyenv/versions/3.13.0/lib/python3.13/site-packages/cda_dl/folder.py", line 162, in get_next_page_url
    page_number = int(match.group(2))
ValueError: invalid literal for int() with base 10: ''
```

**Comment by sabahmax-dev** [comment]
Thanks for reporting this! I’ve opened PR #17, which fixes the folder-download crash caused by trying to parse an empty page number from the next-page URL. It makes the pagination parsing more defensive, so empty or missing page entries no longer raise `ValueError`.
